version: '3'
services:
  t5_web:
    image: java_springv1_t5
    build: .
    ports:
      - "8095:8095"
    volumes:
      - persistent_volume:/app/volumes
    restart: unless-stopped
volumes:
  persistent_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ubuntu/t5-women-in-stem/volumes
